version: "3.9"

services:
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: 'rabbitmqhost'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 20s
      retries: 3


  client:
    container_name: 'client'
    environment:
      - PYTHONUNBUFFERED=1
    build: .
    command: python ./app/client.py
    depends_on:
      rabbit:
        condition: service_healthy
    restart: on-failure

  server:
    container_name: 'server'
    environment:
      - PYTHONUNBUFFERED=1
    build: .
    command: python ./app/server.py
    depends_on:
        rabbit:
          condition: service_healthy
    restart: on-failure

# networks:
#   rabbit_net:
#     driver: bridge